## MSSQL data storage
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
        logs: "true"
    spec:
      containers:
        - name: mssql-server
          image: mcr.microsoft.com/mssql/server:2019-latest
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "sleep 30; /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -U sa -P Test123# -e -Q 'CREATE DATABASE EXAMPLE_DB';"]
          env:
            - name: SA_PASSWORD
              value: Test123#
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: data
              mountPath: /var/lib/mssql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mssql-data-pvc
---
## Service
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    app: mssql-server
spec:
  type: NodePort
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
  selector:
    app: mssql
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
---
