[package]
org = "ballerinax"
name = "mssql"
version = "1.2.1"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "SQLServer", "MSSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mssql"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../native/build/libs/mssql-native-1.2.1.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.2.1-20220201-131400-11b4211.jar"

[[platform.java11.dependency]]
path = "./lib/mssql-jdbc-9.2.0.jre11.jar"
scope = "testOnly"
