[package]
org = "ballerinax"
name = "mssql"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../native/build/libs/mssql-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-@sql.native.version@.jar"

[[platform.java11.dependency]]
path = "./lib/mssql-jdbc-@mssqlDriverVersion@.jar"
scope = "testOnly"
