[package]
org = "ballerinax"
name = "mssql"
version = "1.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/mssql-native-1.0.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.0.0-20211006-122700-7ce6614.jar"

[[platform.java11.dependency]]
path = "./lib/mssql-jdbc-9.2.0.jre11.jar"
scope = "testOnly"
