[package]
org = "ballerinax"
name = "mssql"
version = "1.1.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "SQLServer", "MSSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mssql"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/mssql-native-1.1.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.1.0-20211115-201400-bd1fcce.jar"

[[platform.java11.dependency]]
path = "./lib/mssql-jdbc-9.2.0.jre11.jar"
scope = "testOnly"
