[package]
org = "ballerinax"
name = "mssql"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../mssql-native/build/libs/mssql-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "mssql-native"
version = "@project.version@"

[[platform.java11.dependency]]
path = "@project.path@/repo/bala/ballerina/sql/@stdlib.sql.version@/java11/platform/java11/sql-native-@stdlib.sql.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-sql"
version = "@stdlib.sql.native.version@.jar"

[[platform.java11.dependency]]
path = "./lib/mssql-jdbc-9.2.0.jre11.jar"
artifactId = "mssql-jdbc"
groupId = "mssql"
scope = "testOnly"
version = "9.2.0.jre11"
